# Principal Components Regression

Principal Components Regression is a technique for analyzing multiple regression data that suffer from
multicollinearity. When multicollinearity occurs, least squares estimates are unbiased, but their variances 
are large so they may be far from the true value. By adding a degree of bias to the regression estimates, principal components regression reduces the standard errors. It is hoped that the net effect will be to give more reliable estimates. Another biased regression technique, ridge regression, is also available in NCSS. Ridge regression is the more popular of the two methods.It Provides dimensionality reduction.

Multicollinearity is discussed both in the Multiple Regression chapter and in the Ridge Regression chapter, so we
will not repeat the discussion here. However, it is important to understand the impact of multicollinearity so that
you can decide if some evasive action (like pc regression) would be beneficial.

Import libraries

In [7]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA 
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn import metrics
from sklearn.metrics import r2_score

Import dataset

In [8]:
dataset = pd.read_csv('/home/webtunix/Desktop/Regression/random.csv')
print(len(dataset))

239


Split dataset into x and y

In [9]:
x = dataset.iloc[:,1:4].values
y = dataset.iloc[:,4].values

Split dataset into training and testing sets

In [10]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

Apply PCA model

In [27]:
model =  PCA(n_components=3)
model.fit(X_train,y_train)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

Score of model

In [26]:
model.score(X_train,y_train)

18.9790379307775

Variance ratio of model

In [21]:
print (model.explained_variance_ratio_)

[9.99922830e-01 5.83245117e-05 1.88458612e-05]


Components of model

In [22]:
print model.components_

[[-0.57812177 -0.57480056 -0.57911962]
 [-0.06510906  0.7399828  -0.66946715]
 [ 0.81334865 -0.3493276  -0.46522489]]


# Research Infinite Solutions LLP
by Research Infinite Solutions

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.